  RESPONSE #%response_weight%
    DisplayString(Myself,'Ajout objet aleatoire conditionne du slot %slot% : %item%')
    SetGlobal("ID#%slot%","LOCALS",1)
    SetGlobal("IDR#%index_responses%","LOCALS",1)
    ApplySpellRES("IDDES%slot_id%",Myself)
    GiveItemCreate("%item%",Myself,%item_per_target%,%charge%,0)
    ActionOverride(Myself,SetItemFlags("%item%",%flags%,TRUE))
    XEquipItem("%item%",MySelf,%slot_name%,EQUIP)
    Continue()
