IF
  Global("ID#%slot%","LOCALS",%slot_value_to_reset%)
  Global("IDR#%index_responses%","LOCALS",1)
THEN
  RESPONSE #100
    DisplayString(Myself,%strref_add_conditional%)
    SetGlobal("ID#%slot%","LOCALS",%slot_value_to_dispatch%)
    ApplySpellRES("IDDES%slot_id%",Myself)
    GiveItemCreate("%item%",Myself,%item_per_target%,%charge%,0)
    SetItemFlags("%item%",%flags%,TRUE)
    XEquipItem("%item%",MySelf,%slot_name%,EQUIP)
    Continue()
END
